# Site settings
title: Alexander O'Connor 
email: Alex.OConnor@scss.tcd.ie
description: "Academic Github Site for Alex O&amp;Connor" 
baseurl: ""
twitter_username: uberalex 
github_username:  oconnoat

# Build settings
markdown: kramdown
permalink: pretty
